// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function getClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List products from the Hamoudi Store catalog. Supports optional category filter, in-stock filter, and result limit.",
  inputSchema: {
    category: z.string().optional().describe("Optional product category slug or name (e.g. 'headphones', 'watches')."),
    in_stock_only: z.boolean().optional().describe("If true, return only products currently in stock."),
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of products to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, in_stock_only, limit }) => {
    const supabase = getClient();
    let q = supabase.from("products").select("id, name, description, price, original_price, image, category, badge, in_stock, stock_count").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (category) q = q.ilike("category", category);
    if (in_stock_only) q = q.eq("in_stock", true);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function getClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_products_default = defineTool2({
  name: "search_products",
  title: "Search products",
  description: "Search the Hamoudi Store product catalog by keyword. Matches product name, description, or category (case-insensitive).",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Search keyword (Arabic or English)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = getClient2();
    const like = `%${query}%`;
    const { data, error } = await supabase.from("products").select("id, name, description, price, original_price, image, category, badge, in_stock, stock_count").or(`name.ilike.${like},description.ilike.${like},category.ilike.${like}`).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { query, results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function getClient3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_product_default = defineTool3({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details (including gallery images) for a single product by its UUID.",
  inputSchema: {
    product_id: z3.string().uuid().describe("The product's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_id }) => {
    const supabase = getClient3();
    const [{ data: product, error: pErr }, { data: images }] = await Promise.all([
      supabase.from("products").select("*").eq("id", product_id).maybeSingle(),
      supabase.from("product_images").select("image_url, display_order").eq("product_id", product_id).order("display_order")
    ]);
    if (pErr) return { content: [{ type: "text", text: `Error: ${pErr.message}` }], isError: true };
    if (!product) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    const result = { ...product, gallery: images ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { product: result }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function getClient4() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_categories_default = defineTool4({
  name: "list_categories",
  title: "List categories",
  description: "List all distinct product categories available in the Hamoudi Store catalog with product counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = getClient4();
    const { data, error } = await supabase.from("products").select("category").not("category", "is", null);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const counts = {};
    for (const row of data ?? []) {
      const c = row.category;
      if (c) counts[c] = (counts[c] ?? 0) + 1;
    }
    const categories = Object.entries(counts).map(([name, count]) => ({ name, product_count: count })).sort((a, b) => b.product_count - a.product_count);
    return {
      content: [{ type: "text", text: JSON.stringify(categories, null, 2) }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hamoudi-store-mcp",
  title: "\u062D\u0645\u0648\u062F\u064A \u0633\u062A\u0648\u0631 \u2014 Product Catalog",
  version: "0.1.0",
  instructions: "Public, read-only tools for the Hamoudi Store product catalog. Use `list_categories` to discover categories, `list_products` to browse, `search_products` to find items by keyword (Arabic or English), and `get_product` for full details of one product by UUID. Prices are in EGP. Store info: WhatsApp/Vodafone Cash 01025529130. Delivery across Egypt with Cash-on-Delivery or Vodafone Cash.",
  tools: [list_products_default, search_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
